### ISSUE TITLE
"The Book of John" Study Audio Cutoff

### ISSUE THREAD

**Issue by DominicSears** [USD21Developers/firstprinciples-pwa#3]
I've been getting reports that [The Book of John Study](https://firstprinciples.mobi/lang/en/book-of-john) cuts off around the 7 minute mark

Tested it and that seemed to be the case. I'm pretty sure it would have to do with audio file itself.

**Comment by jasonmcneill** [comment]
The original audios were lost due to an accidental file system cleanup. Some copies were found and replaced the old ones, so hopefully the down time was minimal.  But the copy of the John study may be insufficient.  I wasn't involved in any of these matters, but I'll look into it.

**Comment by jasonmcneill** [comment]
This issue has been addressed, per Jeremy.
